@baseURL = http://localhost:8080
@origin = localhost:8080
@accessToken = eyJhb

### @name register
POST {{baseURL}}/v1/register HTTP/1.1
Content-Type: application/json
Origin: {{origin}}

{
    "email": "ryan1@mail.com",
    "name": "ryan adhitama",
    "password": "12345678"
}


### @name login
POST {{baseURL}}/v1/login HTTP/1.1
Content-Type: application/json
Origin: {{origin}}
# Authorization: Bearer {{accessToken}}

{
    "email": "ryan@mail.com",
    "password": "12345678"
}
